Code_Alap/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, handler404

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeApp.urls')),
    path('', include('toolsApp.urls')),
    path('', include('userApp.urls')),
    path('', include('blogApp.urls')),
]

handler404 = 'homeApp.views.notFound'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.urls import path
from . import views

app_name = 'blogApp'

urlpatterns = [
    # category
    path('add-category/', views.create_category, name='createCategory'),
    path('edit-category/<slug:slug>/', views.edit_category, name='editCategory'),
    path('category/<slug:slug>/', views.single_category, name='singleCategory'),
    path('category/', views.all_categories, name='allCategories'),

    # blog
    path('blog/', views.blogview, name='blog'),
    path('create-blog/', views.create_blog, name='createBlog'),
    path('edit-blog/', views.edit_blog_page, name='editBlogPage'),
    path('edit-blog/<slug:slug>/', views.edit_blog_post, name='editBlogPost'),
    path('<slug:slug>/', views.blog_details, name='blogDetails'),
]

homeApp/urls.py
from django.urls import re_path as url
from django.urls import path
from homeApp.views import *

app_name = 'homeApp'

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('view-contacts/', viewMessages, name='viewMessages'),
    path('delete-message/<int:message_id>/', deleteMessage, name='deleteMessage'),
]


homeApp/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=100)
    contact_mail = models.EmailField(max_length=100)
    subject = models.CharField(max_length=200)
    message = models.TextField(max_length=2000)

    def __str__(self):
        return self.subject

class MailList(models.Model):
    name = models.CharField(max_length=100)
    contact_mail = models.EmailField(max_length=100, unique=True)

    def __str__(self):
        return self.name

homeApp/forms.py
from django import forms
from homeApp.models import Contact, MailList


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

class MailListForm(forms.ModelForm):
    class Meta:
        model = MailList
        fields = "__all__"

homeApp/views.py
from django.shortcuts import render
from homeApp import forms
from homeApp.models import Contact

from django.http import *
from django.urls import reverse

# Create your views here.

def home(request):
    dict = {'title':'Code Alap', 'meta_title':'Code Alap', 'meta_description':'Code Alap, an informative and learning platform. Programming or coding resources and solutions with guidelines. Great for Technology updates.', }
    return render(request, 'homeApp/home.html', context=dict)

def notFound(request, exception):
    dict = {'title':'404'}
    return render(request, 'homeApp/404.html', context=dict)

def subscription(request):
    if request.method == 'POST':
        subs = forms.MailListForm(request.POST)
        if subs.is_valid():
            subs.save(commit=True)
    return render(request, 'base.html', context={})

def contact(request):
    dict = {'title':'Contact with Code Alap'}
    if request.method == 'POST':
        form = forms.ContactForm(request.POST)
        mailForm = forms.MailListForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            dict.update({'success_text':'Message sent successfully!'})
        if mailForm.is_valid():
            mailForm.save(commit=True)
    return render(request, 'homeApp/contact.html', context=dict)

def viewMessages(request):
    dict = {'title':'All Messages From Contact Form'}
    messageList = Contact.objects.all().order_by('-pk')
    dict.update({'messageList': messageList})
    return render(request, 'homeApp/view_contacts.html', context=dict)

def deleteMessage(request, message_id):
    message = Contact.objects.get(pk=message_id).delete()
    return HttpResponseRedirect(reverse('homeApp:viewMessages'))

templates/homeApp/contact.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<form method="POST">
    <div class="form-floating mb-3">
        <input type="text" name="name" class="form-control" id="floatingInput" placeholder="Type Full Name" required>
        <label for="floatingInput">Full Name</label>
    </div>
    <div class="form-floating mb-3">
        <input type="email" name="contact_mail" class="form-control" id="floatingInput" placeholder="name@example.com" required>
        <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" name="subject" class="form-control" id="floatingInput" placeholder="Subject" required>
        <label for="floatingInput">Subject</label>
    </div>
    <div class="form-floating">
        <textarea name="message" class="form-control" placeholder="Leave a message here" id="floatingTextarea2" style="height: 100px" required></textarea>
        <label for="floatingTextarea2">Message</label>
    </div>
    {% csrf_token %}
    <div class="form-floating">
        <input type="submit" name="submit" value="Send Message" class="btn btn-primary mt-2">
    </div>
</form>

{% if success_text %}
<h4 class="alert alert-success mt-2">{{ success_text }}</h4>
{% endif %}
{% endblock %}

templates/homeApp/home.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded text-center">
    <div class="col-sm-8 mx-auto">
        <h1>Code Alap</h1>
        <p>Educative platform for absolute beginners</p>
        <p>
            <a class="btn btn-lg btn-info" href="https://youtube.com/CodeAlap" target="_blank" role="button">Explore Now &raquo;</a>
        </p>
    </div>
</div>

{% endblock %}

templates/homeApp/view_contacts.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}


{% for message in messageList %}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="card mb-2 glass-1">
            <div class="card-header">
                <h6 class="mb-2">Name: {{message.name}} &nbsp; Email: <a href="mailto:{{message.contact_mail}}" class="allB">{{message.contact_mail}}</a></h6>
            </div>
            <div class="card-body">
                <h5 class="card-subtitle mb-2">{{message.subject}}</h5>
                <p class="card-text">{{message.message}}</p>
                <div class="text-end"><a href="{% url 'homeApp:deleteMessage' message_id=message.id %}" class="btn btn-danger">Delete</a></div>
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

{% endfor %}

{% endblock %}