Code_Alap/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, handler404

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeApp.urls')),
    path('', include('toolsApp.urls')),
    path('', include('userApp.urls')),
    path('', include('blogApp.urls')),
]

handler404 = 'homeApp.views.notFound'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.urls import path
from . import views

app_name = 'blogApp'

urlpatterns = [
    # category
    path('add-category/', views.create_category, name='createCategory'),
    path('edit-category/<slug:slug>/', views.edit_category, name='editCategory'),
    path('category/<slug:slug>/', views.single_category, name='singleCategory'),
    path('category/', views.all_categories, name='allCategories'),

    # blog
    path('blog/', views.blogview, name='blog'),
    path('create-blog/', views.create_blog, name='createBlog'),
    path('edit-blog/', views.edit_blog_page, name='editBlogPage'),
    path('edit-blog/<slug:slug>/', views.edit_blog_post, name='editBlogPost'),
    path('<slug:slug>/', views.blog_details, name='blogDetails'),
]

blogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class BlogCategory(models.Model):
    cat_name = models.CharField(max_length=200,)
    cat_slug = models.SlugField(max_length=264, unique=True,)
    cat_description = models.CharField(max_length=160,)
    cat_image = models.URLField(max_length=200,)
    cat_image_up = models.ImageField(upload_to='cat_images', blank=True)

    def __str__(self):
        return self.cat_name

class Blog(models.Model):
    author = models.ForeignKey(User, related_name='post_author', on_delete=models.DO_NOTHING)
    blog_category = models.ForeignKey(BlogCategory, related_name='post_category', null=True, on_delete=models.DO_NOTHING)
    blog_title = models.CharField(max_length=264,)
    slug = models.SlugField(max_length=264, unique=True)
    blog_description = models.CharField(max_length=160,)
    blog_content = models.TextField()
    blog_image = models.ImageField(upload_to='blog_images', blank=True)
    image_url = models.URLField(max_length=160, )
    blog_tags = models.CharField(max_length=200,)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title

blogApp/forms.py
from django import forms
from .models import Blog, BlogCategory


class BlogCategoryForm(forms.ModelForm):
    class Meta:
        model = BlogCategory
        fields = ['cat_name', 'cat_slug', 'cat_description', 'cat_image',]
        
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['author', 'blog_category', 'blog_title', 'slug', 'blog_description', 'image_url', 'blog_tags', 'blog_content',]

blogApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import BlogForm, BlogCategoryForm
from .models import Blog, BlogCategory
from django.db.models import Count

# Create your views here.

def blogview(request):
    blogs = Blog.objects.all()
    dict = {'title':"Code Alap's Blog", 'blogs':blogs}
    return render(request, 'blogApp/blog.html', context=dict)

def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    dict = {'title':blog.blog_title, 'blog':blog}
    return render(request, 'blogApp/blogDetails.html', context=dict)

@login_required
def create_blog(request):
    current_user = request.user
    form = BlogForm()
    valid = False
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            blog_obj = form.save(commit=False)
            blog_obj.author = current_user
            blog_obj.save()
            valid = True
    dict = {'title':"Write Blog", 'form': form, 'valid':valid,}
    return render(request, 'blogApp/createBlog.html', context=dict)

@login_required
def edit_blog_page(request):
    blogs = Blog.objects.all()
    dict = {'title':'Edit Blog Page', 'blogs':blogs,}
    return render(request, 'blogApp/editBlogPage.html', context=dict)

@login_required
def edit_blog_post(request, slug):
    blog = Blog.objects.get(slug=slug)
    form = BlogForm()
    updated = False
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            form = BlogForm(instance=blog)
            updated = True
    dict = {'title':blog.blog_title, 'blog':blog, 'form': form, 'updated':updated,}
    return render(request, 'blogApp/editBlog.html', context=dict)


# Category Section
@login_required
def create_category(request):
    form = BlogCategoryForm()
    created = False
    if request.method == 'POST':
        form = BlogCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            created = True
    dict = {'title':'Create Category', 'form': form, 'created': created}
    return render(request, 'blogApp/addCategory.html', context=dict)

@login_required
def edit_category(request, slug):
    category = BlogCategory.objects.get(cat_slug=slug)
    form = BlogCategoryForm(instance=category)
    updated = False
    if request.method == 'POST':
        form = BlogCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            form = BlogCategoryForm(instance=category)
            updated = True
    dict = {'title':'Edit Category', 'category':category, 'form': form, 'updated': updated}
    return render(request, 'blogApp/editCategory.html', context=dict)

def single_category(request, slug):
    category = BlogCategory.objects.get(cat_slug=slug)
    posts = Blog.objects.all().filter(blog_category=category)
    dict = {'title':category.cat_name, 'category':category, 'posts': posts,}
    return render(request, 'blogApp/singleCategory.html', context=dict)

def all_categories(request):
    categories = BlogCategory.objects.all().annotate(posts_count=Count('post_category'))
    dict = {'title':'Categories of Code Alap', 'categories':categories,}
    return render(request, 'blogApp/allCategories.html', context=dict)

templates/blogApp/addCategory.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        {% if created %}
        <h4 class="alert alert-success">Category Creation Successful!</h4>
        <a class="btn btn-primary" href="{% url 'blogApp:createCategory' %}">Add Category</a>
        <a class="btn btn-primary" href="{% url 'blogApp:allCategories' %}">View Categories</a>
        {% else %}
        <h2>Add Category</h2>
        <form method="POST">
            <div class="form-floating mb-3">
                <input type="text" name="cat_name" class="form-control" id="floatingInput" placeholder="Type Full Name" required>
                <label for="floatingInput">Name</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text" name="cat_slug" class="form-control" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Slug</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text" name="cat_description" class="form-control" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Meta Description</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text" name="cat_image" class="form-control" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Image URL</label>
            </div>
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="submit" name="submit" value="Add Category" class="btn btn-primary mt-2">
            </div>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/blogApp/allCategories.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-4 mx-auto">
        <h2 class="text-center mb-4">All Categories</h2>
        {% if user.is_authenticated %}
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item d-flex justify-content-between align-items-start mb-2">
              <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'blogApp:singleCategory' slug=category.cat_slug %}" style="text-decoration: none;">{{category.cat_name}}</a></div>
                <a href="{% url 'blogApp:editCategory' slug=category.cat_slug %}" class="btn btn-primary btn-sm">Edit</a>
              </div>
              <span class="badge bg-primary rounded-pill">{{category.posts_count}}</span>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <ul class="list-group">
            {% for category in categories %}
            <a href="{% url 'blogApp:singleCategory' slug=category.cat_slug %}" style="text-decoration: none; color: #212529;">
              <li class="list-group-item d-flex justify-content-between align-items-start mb-2">
                <div class="ms-2 me-auto">
                  <div class="fw-bold">{{category.cat_name}}</div>
                </div>
                <span class="badge bg-primary rounded-pill">{{category.posts_count}}</span>
              </li>
            </a>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/blogApp/blog.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

{% comment %}
<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h1>Code Alap Blog</h1>
    </div>
</div>
{% endcomment %}

<div class="mt-4">
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for blog in blogs %}
        <div class="col">
          <div class="card h-100">
            <img src="{{blog.image_url}}" class="card-img-top" alt="Code Alap">
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'blogApp:blogDetails' slug=blog.slug %}" style="text-decoration: none; color: #212529;">{{blog.blog_title}}</a></h5>
              <p class="card-text">{{blog.blog_description}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/blogApp/blogDetails.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% load custom_filters %}
{% block body_block %}
<div class="col-md-12 text-center">
    <img src="{{blog.image_url}}" class="text-center" alt="..." height="400px" width="800px">
</div>

<div class="row mt-3">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="card" style="background:none; border:none;">
            <div class="card-body">
              <h1 class="card-title text-center mb-5">{{blog.blog_title}}</h1>
              <p class="card-text">{{blog.blog_content | markdown | safe}}</p>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

{% endblock %}

templates/blogApp/createBlog.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-12 mx-auto">
        {% comment %}
        {% if valid %}
        <h4 class="alert alert-success">Successfully Published!</h4>
        <a class="btn btn-primary btn-sm ml-2" href="{% url 'blogApp:createBlog' %}">Write Another</a>
        <a class="btn btn-primary btn-sm ml-2" href="{% url 'blogApp:blog' %}">Blog Page</a>
        {% else %}
        <h2 class="text-center">What's on your mind?</h2>
        <div class="mt-4">
            {{form.author}}
            <form method="POST" enctype="multipart/form-data">
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Title</label>
                    <input type="text" name="blog_title" class="form-control" id="exampleFormControlInput1" placeholder="Enter Blog Title" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Slug</label>
                    <input type="text" name="slug" class="form-control" id="exampleFormControlInput1" placeholder="Enter Blog Slug" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Meta Description (max 160 char)</label>
                    <input type="text" name="blog_description" class="form-control" id="exampleFormControlInput1" placeholder="Enter Meta Description" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Image URL</label>
                    <input type="text" name="image_url" class="form-control" id="exampleFormControlInput1" placeholder="Enter Image URL" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Blog tags (meta keywords)</label>
                    <input type="text" name="blog_tags" class="form-control" id="exampleFormControlInput1" placeholder="Enter meta Tags" required>
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Content</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="15"></textarea>
                </div>
                {% csrf_token %}
                <div class="mb-3">
                    <input type="submit" name="submit" value="Publish" class="btn btn-primary mt-2">
                </div>
            </form>
        </div>
        {% endif %}
        {%endcomment %}
        
        {% if valid %}
        <h4 class="alert alert-success">Successfully Published!</h4>
        <a class="btn btn-primary btn-sm ml-2" href="{% url 'blogApp:createBlog' %}">Write Another</a>
        <a class="btn btn-primary btn-sm ml-2" href="{% url 'blogApp:blog' %}">Blog Page</a>
        {% else %}
        <form method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Publish</button>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/blogApp/editBlog.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-12 mx-auto">
        <h2 class="text-center mb-4">Edit Blog</h2>
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <button type="submit">Update</button>
        </form>
    </div>
</div>

{% endblock %}

templates/blogApp/editBlogPage.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h2 class="text-center mb-4">All Posts</h2>
        <ul class="list-group">
            {% for blog in blogs %}
            <a href="{% url 'blogApp:editBlogPost' slug=blog.slug %}" style="text-decoration:none; color:#212529;">
            <li class="list-group-item d-flex justify-content-between align-items-start mb-2">
              <div class="ms-2 me-auto">
                <div class="fw-bold">{{blog.blog_title}}</div>
              </div>
            </li>
            </a>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

templates/blogApp/editCategory.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h2 class="text-center mb-4">Edit Category</h2>
        {% if updated %}
        <h4 class="alert alert-success">Category Updated!</h4>
        <a href="{% url 'blogApp:editCategory' slug=category.cat_slug %}" class="btn btn-primary">Edit Again</a>
        <a href="{% url 'blogApp:allCategories' %}" class="btn btn-primary">All Category</a>
        {% else %}
        <form method="POST">
            <div class="mb-3">
              <label for="exampleInput1" class="form-label">Name</label>
              <input type="text" name="cat_name" class="form-control" id="exampleInput1" value="{{category.cat_name}}">
            </div>
            <div class="mb-3">
                <label for="exampleInput2" class="form-label">Slug</label>
                <input type="text" name="cat_slug" class="form-control" id="exampleInput2" value="{{category.cat_slug}}">
            </div>
            <div class="mb-3">
                <label for="exampleInput3" class="form-label">Meta Description</label>
                <input type="text" name="cat_description" class="form-control" id="exampleInput3" value="{{category.cat_description}}">
            </div>
            <div class="mb-3">
                <label for="exampleInput4" class="form-label">Image URL</label>
                <input type="text" name="cat_image" class="form-control" id="exampleInput4" value="{{category.cat_image}}">
            </div>
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/blogApp/singleCategory.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <div class="card text-center">
            <div class="card-body">
              <h1 class="card-title">{{category.cat_name}}</h1>
              <p class="card-text"><b>{{category.cat_description}}</b></p>
            </div>
        </div>
    </div>
</div>
<div class="row row-cols-1 row-cols-md-4 g-4 mt-2">
    {% for post in posts %}
    <div class="col">
        <a href="{% url 'blogApp:blogDetails' slug=post.slug %}" style="text-decoration: none; color: #212529;">
            <div class="card h-100">
                <img src="{{post.image_url}}" class="card-img-top" alt="Code Alap">
                <div class="card-body">
                <h5 class="card-title">{{post.blog_title}}</h5>
                <p class="card-text">{{post.blog_description|safe|slice:":120"}}...</p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

{% endblock %}