Code_Alap/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, handler404

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeApp.urls')),
    path('', include('toolsApp.urls')),
    path('', include('userApp.urls')),
    path('', include('blogApp.urls')),
]

handler404 = 'homeApp.views.notFound'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.urls import path
from . import views

app_name = 'blogApp'

urlpatterns = [
    # category
    path('add-category/', views.create_category, name='createCategory'),
    path('edit-category/<slug:slug>/', views.edit_category, name='editCategory'),
    path('category/<slug:slug>/', views.single_category, name='singleCategory'),
    path('category/', views.all_categories, name='allCategories'),

    # blog
    path('blog/', views.blogview, name='blog'),
    path('create-blog/', views.create_blog, name='createBlog'),
    path('edit-blog/', views.edit_blog_page, name='editBlogPage'),
    path('edit-blog/<slug:slug>/', views.edit_blog_post, name='editBlogPost'),
    path('<slug:slug>/', views.blog_details, name='blogDetails'),
]

homeApp/urls.py
from django.urls import re_path as url
from django.urls import path
from homeApp.views import *

app_name = 'homeApp'

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('view-contacts/', viewMessages, name='viewMessages'),
    path('delete-message/<int:message_id>/', deleteMessage, name='deleteMessage'),
]


userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('singin/', views.sign_in, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='editProfile'),
    path('author/<username>/', views.author_profile, name='authorProfile'),
]

userApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.DO_NOTHING)
    profile_pic = models.ImageField(upload_to='profile_pics')

userApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

# class ProfilePic(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ('profile_pic',)

userApp/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, UserProfileChange

# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {'title':'Create Account', 'form': form, 'registered':registered,}
    return render(request, 'userApp/signup.html', context=dict)

def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('userApp:dashboard'))    
    dict = {'title':'Sign in your account', 'form':form}
    return render(request, 'userApp/signin.html', context = dict)

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('homeApp:home'))

@login_required
def edit_profile(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    dict = {'title':'Edit Profile', 'form': form,}
    return render(request, 'userApp/editProfile.html', context=dict)

@login_required
def author_profile(request, username):
    dict = {'title':'Author Profile',}
    return render(request, 'userApp/authorProfile.html', context=dict)


def dashboard(request):
    dict = {'title': 'Dashboard',}
    return render(request, 'userApp/dashboard.html', context= dict)



templates/userApp/authorProfile.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h2 class="text-center">Author Profile</h2>
        <hr>
        <h5 class="mt-3">Name: {{user.first_name}} {{user.last_name}}</h5>
        
    </div>
</div>

{% endblock %}

templates/userApp/dashboard.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h2 class="text-center mb-4">Author Dashboard</h2>
        <h5>Username: <a href="{% url 'userApp:authorProfile' username=user.username %}" style="text-decoration: none;">{{ user.username }}</a> <a href="{% url 'userApp:editProfile' %}" class="btn btn-info btn-sm">Edit</a></h5>
        <hr>
        <br>
        
        <a href="{% url 'blogApp:createBlog' %}" class="btn btn-primary">Write</a>
        <a href="{% url 'blogApp:editBlogPage' %}" class="btn btn-primary">Edit Posts</a>
        <a href="{% url 'blogApp:createCategory' %}" class="btn btn-primary">Add Category</a>
        <a href="{% url 'blogApp:allCategories' %}" class="btn btn-primary">All Category</a>
        <a href="{% url 'homeApp:viewMessages' %}" class="btn btn-primary">Messages</a>
    </div>
</div>

{% endblock %}

templates/userApp/editProfile.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h2 class="text-center">Edit Profile Info</h2>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning btn-sm">Change</button>
        </form>
        <!-- <form method="POST">
            <div class="form-floating mb-3">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="username">
                <label for="floatingInput">username</label>
            </div>
            <div class="form-floating mb-3">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="email">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="row g-2">
                <div class="col-md">
                    <div class="form-floating mb-3">
                        <input type="text" name="first_name" class="form-control" id="floatingInput" placeholder="first name">
                        <label for="floatingInput">First Name</label>
                    </div>
                </div>
                <div class="col-md">
                    <div class="form-floating mb-3">
                        <input type="text" name="last_name" class="form-control" id="floatingInput" placeholder="last name">
                        <label for="floatingInput">Last Name</label>
                    </div>
                </div>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="submit" name="submit" value="Create Account" class="btn btn-primary mt-2">
            </div>
        </form> -->
    </div>
</div>

{% endblock %}

templates/userApp/signin.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        <h2>Account Sign in</h2>
        <form method="POST">
            <div class="form-floating mb-3">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Type Full Name" required>
                <label for="floatingInput">username</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Enter Password</label>
            </div>
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="submit" name="submit" value="Sign in" class="btn btn-primary mt-2">
            </div>
        </form>
        <p>New User? <a href="{% url 'userApp:signup' %}">Create Account</a></p>
    </div>
</div>

{% endblock %}

templates/userApp/signup.html
{% extends 'base.html' %}
{% block title_block %} {{title}} {% endblock %}
{% load static %}
{% block body_block %}

<div class="glass-1 p-5 rounded">
    <div class="col-sm-8 mx-auto">
        {% if registered %}
        <h4 class="alert alert-success">Account Creation Successful! <a href="{% url 'userApp:signin' %}">Login here</a></h4>
        {% else %}
        <h2>Create Account</h2>
        <form method="POST">
            <div class="form-floating mb-3">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Type Full Name" required>
                <label for="floatingInput">username</label>
            </div>
            <div class="form-floating mb-3">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com" required>
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password1" class="form-control" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Enter Password</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Password" required>
                <label for="floatingPassword">Re-enter Password</label>
            </div>
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="submit" name="submit" value="Create Account" class="btn btn-primary mt-2">
            </div>
        </form>
        <p>Already an account? <a href="{% url 'userApp:signin' %}">Login here</a></p>
        {% endif %}
    </div>
</div>

{% endblock %}