Code_Alap/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, handler404

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeApp.urls')),
    path('', include('toolsApp.urls')),
    path('', include('userApp.urls')),
    path('', include('blogApp.urls')),
]

handler404 = 'homeApp.views.notFound'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.urls import path
from . import views

app_name = 'blogApp'

urlpatterns = [
    # category
    path('add-category/', views.create_category, name='createCategory'),
    path('edit-category/<slug:slug>/', views.edit_category, name='editCategory'),
    path('category/<slug:slug>/', views.single_category, name='singleCategory'),
    path('category/', views.all_categories, name='allCategories'),

    # blog
    path('blog/', views.blogview, name='blog'),
    path('create-blog/', views.create_blog, name='createBlog'),
    path('edit-blog/', views.edit_blog_page, name='editBlogPage'),
    path('edit-blog/<slug:slug>/', views.edit_blog_post, name='editBlogPost'),
    path('<slug:slug>/', views.blog_details, name='blogDetails'),
]

homeApp/urls.py
from django.urls import re_path as url
from django.urls import path
from homeApp.views import *

app_name = 'homeApp'

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('view-contacts/', viewMessages, name='viewMessages'),
    path('delete-message/<int:message_id>/', deleteMessage, name='deleteMessage'),
]


toolsApp/urls.py
from django.urls import re_path as url
from django.urls import path
from toolsApp.views import *

app_name = 'toolsApp'

urlpatterns = [
    path('tools/', tools, name='tools'),
    path('github-user-viewer/', githubUserView, name='githubUserView')
]

userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('singin/', views.sign_in, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='editProfile'),
    path('author/<username>/', views.author_profile, name='authorProfile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- meta tags -->
  <!-- Primary Meta Tags -->
  <title>{% block title_block %} {% endblock %}</title>
  <meta name="title" content="{{meta_title}}">
  <meta name="description" content="{{meta_description}}">
  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{meta_title}}">
  <meta property="og:description" content="{{meta_description}}">
  <meta property="og:image" content="{{meta_img}}">
  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:title" content="{{meta_title}}">
  <meta property="twitter:description" content="{{meta_description}}">
  <meta property="twitter:image" content="{{meta_img}}">
  <!-- end meta tags -->

  <!-- favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

  <!-- static files -->
  <link rel="stylesheet" href="{% static 'css/homeApp/home.css' %}">
  <link rel="stylesheet" href="{% static 'css/toolsApp/tools.css' %}">

</head>


<body class="d-flex flex-column min-vh-100">

  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'homeApp:home' %}">Code Alap</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogApp:blog' %}"><b>Blog</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'toolsApp:tools' %}"><b>Tools</b></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" class="btn btn-danger" href="{% url 'userApp:dashboard' %}"><b>Dashboard</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" class="btn btn-danger" href="{% url 'userApp:logout' %}"><b>logout</b></a>
          </li>
          {% endif %}
        </ul>
        <a href="https://facebook.com/codealap" target="_blank" class="btn btn-warning">Facebook</a>
      </div>
    </div>
  </nav>
  <div class="container mt-4">
      {% block body_block %}
      {% endblock %}
  </div>
  <div class="container mt-auto">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-3 mb-0 text-muted">&copy; <script>document.write(new Date().getFullYear())</script> Code Alap. All rights reserved.</p>
  
      <form>
        <div class="d-flex flex-column flex-sm-row w-100 gap-2">
          <form method="POST">
            <input id="newsletter" type="text" class="form-control" placeholder="Email address" name="contact_mail">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" name="submit" value="Submit">
          </form>
        </div>
      </form>
  
      <ul class="nav col-md-5 justify-content-end">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        <li class="nav-item"><a href="{% url 'homeApp:contact' %}" class="nav-link px-2 text-muted">Contact</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Privacy Policy</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Terms&Conditions</a></li>
      </ul>
    </footer>
  </div>
</body>
</html>